#!/bin/python3

import math
import os
import random
import re
import sys
#import string
# Complete the solve function below.
def solve(s):
    return ' '.join(i.capitalize() for i in s.split(' '))
    #anothe way to solve this is : """return string.capwords(s,' ')""" but we have to import string before


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
